export const apps = [
  {
    name: 'zhblogs-deploy',
    port: '9900',
    exec_mode: 'fork',
    script: './apps/deploy/dist/index.js',
    node_args: '--env-file ./.env',
    merge_logs: true,
    out_file: "./logs/deploy/pm2-out.log",
    error_file: "./logs/deploy/pm2-error.log",
  },
  {
    name: 'zhblogs-server',
    port: '9901',
    exec_mode: 'cluster',
    instances: 'max',
    script: './apps/server/dist/index.js',
    node_args: '--env-file ./.env',
    env: {
      SHUTDOWN_TIMEOUT: 10000,
      SHUTDOWN_CHECK_INTERVAL: 1000,
      PM2_KILL_SIGNAL: 'SIGINT',
    },
    kill_timeout: 15000,
    wait_ready: true,
    listen_timeout: 5000,
    merge_logs: true,
    out_file: "./logs/server/pm2-out.log",
    error_file: "./logs/server/pm2-error.log",
  },
  {
    name: 'zhblogs-web',
    port: '9902',
    exec_mode: 'cluster',
    instances: 'max',
    script: './apps/web/dist/server/index.mjs',
    node_args: '--env-file ./.env',
    merge_logs: true,
    out_file: "./logs/web/pm2-out.log",
    error_file: "./logs/web/pm2-error.log",
  }
];
